Home page
facg3/gaza-works-online pull request #100
Opened 2018-01-16 15:48 UTC by sultanassi95

## Relates to: #99 
### **What Happened?**
- This branch was the kick-of of our project, building the main landing page, through front-end to back-end and initializing server.
- Initialized HANDLEBARS.
- Made the first face of home page for route ('/') with HBS: html, and css.
- Created and Applied controller (homePage.js) for route: ('/').
- Made test on route: ('/')
- sync'd with travis successfully.

2018-01-16 17:08 UTC, mohanagy approved these changes

2018-01-16 17:55 UTC, NouraldinS approved these changes

2018-01-17 06:19 UTC, matthewdking requested changes

2018-01-17 06:19 UTC, matthewdking commented on public/css/header.css
> +
inconsistent spacing sorry

2018-01-17 06:20 UTC, matthewdking approved these changes
Not a blocker lets get it merged :twisted_rightwards_arrows:

2018-01-17 06:21 UTC, merged