Sign Up
facg3/gaza-works-online pull request #107
Opened 2018-01-18 13:32 UTC by sultanassi95

#50 #51 #53 #52 #55 

## Modified:
- ./src/app.js
- ./src/controllers/mainController.css

## Added:
### Folders:
- ./public/js

### Files:
- ./src/controllers/signUp.js
- ./src/views/signUp.hbs
- ./src/public/css/signUp.css
- ./src/public/js/signUp.js

## Packages:
- added: body-parse

2018-01-19 05:30 UTC, Walidmash requested changes

2018-01-19 05:30 UTC, Walidmash commented on public/js/signUp.js
> +select('#submit-btn').addEventListener('click', (event) => {
dont listen to 'click' event in forms, use 'submit' because it includes pressing Enter

2018-01-19 05:30 UTC, Walidmash commented on public/js/signUp.js
> +  return null;
Why return null? I think there is no need for it.

2018-01-19 05:30 UTC, Walidmash commented on public/js/signUp.js
> +  const usrData = {
Why is there two constants have the same value in the same function (usrData and signUpData)?

2018-01-19 05:30 UTC, Walidmash commented on public/js/signUp.js
> +    return alert('Username must be at least 5 characters, contains only alphanumericals.');
Don't use alert and console.log to log error, show this validation error in a 'span' note for example
Note: modal is not a good UX to show  validation errors, as you will get more than one validation error at the same time, and its good to keep user focus in one view only.

2018-01-19 05:30 UTC, Walidmash commented on public/css/signUp.css
> +  h1 {
Is this working? I tried it before and I don't remember it worked with me.

2018-01-19 07:33 UTC, NoureldeanSaed commented on public/js/signUp.js
> +  return null;
@Walidmash You absolutely have every right with every comment! Thanks man for reviewing this on your day off! This already had saved us a few hours from the coming days! Thnx again!

2018-01-19 07:36 UTC, NoureldeanSaed commented on public/css/signUp.css
> +html, body {
I don't think you should use tag selectors, they cause some problems sometimes, alternatively you could make a div right under the body containing the body's contents and give it a classname an css the last.

2018-01-19 07:40 UTC, NoureldeanSaed commented on public/js/signUp.js
> +const validateEmail = email => email.match(/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/);
Are you sure this is a valid email address? Sorry to tell you that it works for valid emails, but it doesn't for some invalid ones.

2018-01-19 07:41 UTC, NoureldeanSaed commented on src/app.js
> +app.use(bodyParser.raw({ type: () => true }));
Are you sure we still need this line?

2018-01-19 07:44 UTC, NouraldinS requested changes
Changes requested are in the comments, each shouldn't take more than a minute. So in general, good job mate.

2018-01-19 07:44 UTC, NoureldeanSaed commented on src/app.js
> +  console.log(req.method);
Sorry but remove the logs.

2018-01-20 10:57 UTC, sultanassi95 commented on public/js/signUp.js
> +  return null;
@Walidmash it's an ESlinter tip, a function with args must have a return value for consistency.

2018-01-20 10:58 UTC, sultanassi95 commented on public/css/signUp.css
> +html, body {
hmm, that might happen yes, but only if we have more than one body and html elements :walking_man:

2018-01-20 10:58 UTC, sultanassi95 commented on src/app.js
> +app.use(bodyParser.raw({ type: () => true }));
yes we do :sob:

2018-01-20 10:59 UTC, sultanassi95 commented on src/app.js
> +  console.log(req.method);
it's a checker mate :duck:

2018-01-20 21:21 UTC, mohanagy requested changes

2018-01-20 21:21 UTC, mohanagy commented on public/js/signUp.js
> +  const isValidUsr = validateUsr(signUpData.username);
you can do this 
`const {pwd,pwdConfirmation,email} = signUpDate ;`
instead of doing `signUpData. signUpData. signUpData. signUpData.`

2018-01-20 21:21 UTC, mohanagy commented on public/js/signUp.js
> +    .then(err => console.log(err));
do we handle the error inside `then`?
so what the use of `catch `

2018-01-20 21:21 UTC, mohanagy commented on src/controllers/signUp.js
> +  res.send(req.body);
actually, while you didn't your code and you want to make a something like base construction 
you can use `//ToDo:`

2018-01-20 21:21 UTC, mohanagy commented on src/views/signUp.hbs
> +            <input type="password" id="pwd"placeholder="Password"/>
i think you need a space  between your attributes 
`     <input type="password" id="pwd" placeholder="Password"/>`

2018-01-21 13:13 UTC, yahyaHB approved these changes
finally!!

2018-01-21 14:50 UTC, NoureldeanSaed commented on src/database/dbBuild.js
> +  return console.log('Database have been built.', res);
Remove console.log

2018-01-21 14:51 UTC, NoureldeanSaed commented on src/controllers/signUp.js
> +    email: req.body.email,
Where is password confirmation? You should have that to back-end-validate.

2018-01-21 14:53 UTC, NoureldeanSaed commented on src/tests/controllers/signUp.js
> +const postOKSignUp = () => {
I really don't want to be an ass, but is this the best name you can come up with?

2018-01-21 14:54 UTC, NouraldinS requested changes
- nodemon, supertest, tap-spec and tape are dev-dependencies not dependencies.
- Password Confirmation validation

2018-01-21 15:36 UTC, mohanagy requested changes

2018-01-21 15:36 UTC, mohanagy commented on package.json
> +    "fs": "0.0.1-security",
??? what this

2018-01-21 15:36 UTC, mohanagy commented on package.json
> +    "supertest": "^3.0.0",
why we need these modules in the production env ?

2018-01-22 03:46 UTC, Walidmash approved these changes

2018-01-22 03:46 UTC, Walidmash commented on src/views/signUp.hbs
> +            <input type="password" id="pwd"placeholder="Password"/>
and you need to make them ```required``` fields.

2018-01-22 04:17 UTC, Walidmash commented on package.json
> +    "fs": "0.0.1-security",
lol

2018-01-22 06:33 UTC, NouraldinS approved these changes

2018-01-22 06:33 UTC, NoureldeanSaed commented on src/controllers/signUp.js
> +    email: req.body.email,
nvm..

2018-01-22 06:35 UTC, sultanassi95 commented on src/controllers/signUp.js
> +    email: req.body.email,
:+1:

2018-01-22 09:29 UTC, merged