Login status
facg3/gaza-works-online pull request #108
Opened 2018-01-21 12:36 UTC by NoureldeanSaed

Login progress: front and back end verification, backend response after connecting to database with a correct login (if correct password and username) or not

RELATES #59

2018-01-21 12:37 UTC, yahyaHB approved these changes

2018-01-21 13:09 UTC, sultanassi95 requested changes

2018-01-21 13:09 UTC, sultanassi95 commented on src/database/queries/compareLogin.js
> +        else if (!bResult) return cb(null, 'wrongLogin');
should test for bResult in the handler, try keep queries clean?

2018-01-21 14:37 UTC, sultanassi95 approved these changes
:+1:

2018-01-21 16:55 UTC, mohanagy requested changes
can you share with us , the env file ?

2018-01-21 16:55 UTC, mohanagy commented on public/js/login.js
> +          console.log('aaaaaaaaaaaaaaaaaa');
:fire:

2018-01-21 16:55 UTC, mohanagy commented on src/controllers/mainController.js
> +const errors = require('./errors');
you can use `const {e404,e500} = require('./errors');`

2018-01-21 16:55 UTC, mohanagy commented on src/database/dbConnection.js
> +const env = require('env2');
you can use  `const env = require('env2')('config.env');`

2018-01-21 16:55 UTC, mohanagy commented on src/database/dbConnection.js
> +const options = {
i think , instead of split the url 
you can pass it to `connectionString` 
so it will be 
` const options = {`
 `connectionString: 'your url ',`
` max:'max connection'`
`}
`
it will short many lines

2018-01-21 16:55 UTC, mohanagy commented on src/libs/loginValidator.js
> +  const { password } = req.body;
you can do this 
`  const { username,password } = req.body;`
instead of
 ` const { username } = req.body;`
`const { password } = req.body;`

2018-01-21 16:55 UTC, mohanagy commented on src/tests/controllers/loginTests.js
> +        console.log(err);
remove this line

2018-01-21 16:55 UTC, mohanagy commented on src/tests/tests.js
> +const loginTest = require('./controllers/loginTests');
`const {
postLoginCorrect,postLoginFalseUsername,
postLoginFalsePassword,postLoginMissingUsername,postLoginMissingPassword
} = require('./controllers/loginTests');`

2018-01-21 17:00 UTC, NoureldeanSaed commented on public/js/login.js
> +          console.log('aaaaaaaaaaaaaaaaaa');
@mohanagy 
DATABASE_URL=postgres://ocmlyhkkstwkmc:2276125ad2e7021edafc06087df3e1a423795c58caa4440161218172d233a651@ec2-54-221-251-195.compute-1.amazonaws.com:5432/deqgeaft84qrca

2018-01-21 17:02 UTC, NoureldeanSaed commented on src/controllers/mainController.js
> +const errors = require('./errors');
We can but it would be more readable I think to make it the way it is, it's like I'm specifying that this is from errors and then specifying what error it is.

2018-01-21 17:04 UTC, NoureldeanSaed commented on src/database/dbConnection.js
> +const env = require('env2');
You can help out by reviewing @sultanassi95  last pull request, maybe generosity would even take you to merging it, just saying.
Anyway he made this file and I just didn't want any merge conflicts. But I already used that in some other piece of code.

2018-01-21 17:06 UTC, NoureldeanSaed commented on src/libs/loginValidator.js
> +  const { password } = req.body;
Good point.

2018-01-21 17:09 UTC, NoureldeanSaed commented on src/tests/controllers/loginTests.js
> +        console.log(err);
Done.

2018-01-21 17:11 UTC, NoureldeanSaed commented on src/tests/tests.js
> +const loginTest = require('./controllers/loginTests');
Again you're right it could be done this way, but I insist on keeping it the same as it would be more readable code @mohanagy 
Nothing personal man but I already know object destructuring. But here unless it would be faster for a server, I'm not changing it.

2018-01-21 21:10 UTC, mohanagy commented on public/js/login.js
> +          console.log('aaaaaaaaaaaaaaaaaa');
seriously?
this is a public repo 
so anyone can read this comment 
and this means , maybe someone is deleting  your database  right now

2018-01-21 21:12 UTC, mohanagy commented on src/controllers/mainController.js
> +const errors = require('./errors');
actually, we can know using the name of the file 
and i think its good practice to use the way i told you

2018-01-21 21:23 UTC, mohanagy commented on src/database/dbConnection.js
> +const env = require('env2');
1. -_-
3. when you create a new branch you should follow this path 
` Current branch ----> checkout to master ---> pull from master on GitHub to your local ---> checkout to the new branch ` 
this will let you avoid to carry your teammates' code and this moment I will stop review their code in your pull request

2018-01-22 04:15 UTC, Walidmash requested changes
Good job Nour :smile:

2018-01-22 04:15 UTC, Walidmash commented on public/css/login.css
> +    background-color: rgba(0,0,0,0);
use ```background: none;```

2018-01-22 04:15 UTC, Walidmash commented on src/controllers/errors.js
> +const e500 = (req, res) => {
Is this middleware working !?
Error middleware's first argument is ```error```

2018-01-22 04:15 UTC, Walidmash commented on src/controllers/login.js
> +  // }
remove commented code

2018-01-22 04:15 UTC, Walidmash commented on src/controllers/login.js
> +    res.cookie('somename', 'somevalue', { maxAge: 6000 });
hahaha what is this cookie?

2018-01-22 04:15 UTC, Walidmash commented on src/libs/bcrypt.js
> +      return cb(null, hash);
No need for all of that, you can just write 
```bcryptjs.hash(pwd, salt, cb)```

2018-01-22 04:15 UTC, Walidmash commented on src/libs/bcrypt.js
> +    return cb(null, result);
Again, you can remove of this and just add cb as an argument like this:
```bcryptjs.compare(password, hashedPassword, cb)```

2018-01-22 04:15 UTC, Walidmash commented on public/css/login.css
> +    /*position: absolute;*/
Remove commented code.

2018-01-22 06:17 UTC, NoureldeanSaed commented on src/controllers/login.js
> +    res.cookie('somename', 'somevalue', { maxAge: 6000 });
So sorry, I pushed this file by mistake, I'm working on it.

2018-01-22 06:21 UTC, NoureldeanSaed commented on src/libs/bcrypt.js
> +    return cb(null, result);
That did shorten the code, thanks!

2018-01-22 07:01 UTC, mohanagy approved these changes

2018-01-22 09:29 UTC, Walidmash commented on src/controllers/errors.js
> +const e500 = (req, res) => {
@NoureldeanSaed  did you see this ?

2018-01-22 11:39 UTC, closed without merging