Login branch2
facg3/gaza-works-online pull request #109
Opened 2018-01-22 10:21 UTC by NoureldeanSaed

This is the same as loginBranch #108, but it has conflicts with the master, nothing serious hopefully, everything solved.

2018-01-22 12:06 UTC, sultanassi95 requested changes

2018-01-22 12:06 UTC, sultanassi95 commented on src/controllers/login.js
> +    if (err) throw new Error(err);
I think u need to send a response with status (500) instead.

2018-01-22 12:06 UTC, sultanassi95 commented on src/controllers/mainController.js
> +router.use(Error404NotFound);
Should this middleware be used on app.js?

2018-01-22 12:06 UTC, sultanassi95 commented on src/database/queries/compareLogin.js
> +    else if (dbResult.rowCount === 0) return cb(null, 'userNotFound');
why not testing the dbResult on the handler that invokes this query instead of doing it both here and there?

2018-01-22 12:06 UTC, sultanassi95 commented on src/libs/loginValidator.js
> +  password: joi.string().regex(/^[a-zA-Z0-9]{8,}$/).required()
password would have non-alpha charchters in it right?

2018-01-22 12:06 UTC, sultanassi95 commented on src/libs/loginValidator.js
> +  password: joi.string().regex(/^[a-zA-Z0-9]{8,}$/).required()
check out signUpValidator.js

2018-01-22 12:06 UTC, sultanassi95 commented on src/tests/controllers/loginTests.js
> +const supertest = require('supertest');
good testing :+1:

2018-01-22 12:08 UTC, NoureldeanSaed commented on src/controllers/login.js
> +    if (err) throw new Error(err);
This is already what's happening :p

2018-01-22 12:08 UTC, NoureldeanSaed commented on src/controllers/mainController.js
> +router.use(Error404NotFound);
Yep.

2018-01-22 12:14 UTC, yahyaHB commented on src/controllers/login.js
> +    if (err) throw new Error(err);
@sultanassi95  I think you're right 
@NoureldeanSaed  you should've sent it 500 status

2018-01-22 12:14 UTC, yahyaHB commented on src/controllers/mainController.js
> +router.use(Error404NotFound);
yeah

2018-01-22 12:16 UTC, yahyaHB reviewed
good job Noureldean

2018-01-22 12:16 UTC, yahyaHB commented on src/database/queries/compareLogin.js
> +        return cb(null, bResult);
I think u should respond with a plain understandable err message

2018-01-22 19:09 UTC, mohanagy requested changes
please recheck you code again , 
i will continue the review when you push again

2018-01-22 19:09 UTC, mohanagy commented on package.json
> +    "jsonwebtoken": "^8.1.0",
where did u use this module ?

2018-01-22 19:09 UTC, mohanagy commented on public/js/login.js
> +  const usernameRegex = /^\w{5,}/;
no need to declare these variables every time u call the function

2018-01-22 19:09 UTC, mohanagy commented on src/controllers/login.js
> +    if (err) throw new Error(err);
WTF ! sure ?

2018-01-22 19:09 UTC, mohanagy commented on package.json
>    "dependencies": {
add script command for creating   and dropping the database

2018-01-22 19:09 UTC, mohanagy commented on package.json
>    "dependencies": {
your `db-build` doesn't return any error if there an error

2018-01-22 19:09 UTC, mohanagy commented on src/controllers/login.js
> +    if (err) throw new Error(err);
your server will crash

2018-01-22 19:09 UTC, mohanagy commented on src/libs/loginValidator.js
> +  password: joi.string().regex(/^[a-zA-Z0-9]{8,}$/).required()
Missing trailing comma

2018-01-23 15:36 UTC, mohanagy requested changes

2018-01-23 15:36 UTC, mohanagy commented on src/database/build.sql
> +DROP TABLE users, projects, proposals, comments, categories, skills IF EXISTS;
WTF !
i told you to fix this problem

2018-01-23 15:36 UTC, mohanagy commented on public/js/login.js
> +        credentials: 'include',
do we need this line

2018-01-23 15:36 UTC, mohanagy commented on src/controllers/log.js
> +    if (err) throw new Error(err);
don't use throw to handle your error

2018-01-23 15:36 UTC, mohanagy commented on src/controllers/log.js
> +        // res.redirect(302, '/');
remove this lines

2018-01-23 15:36 UTC, mohanagy commented on src/controllers/log.js
> +  // res.render('homePage', { title: 'Gaza Works Online - Home', style: 'homePage', logged: false });
remove this line

2018-01-23 15:36 UTC, mohanagy commented on src/database/build.sql
> +  project_id INTEGER REFERENCES projects(id) NOT NULL,
you reference here to table not created yet

2018-01-23 15:36 UTC, mohanagy commented on src/database/build.sql
> +  category_id INTEGER REFERENCES categories(id),
same here

2018-01-23 15:36 UTC, mohanagy commented on src/database/build.sql
> +)
semi column missed here

2018-01-23 15:36 UTC, mohanagy commented on src/controllers/log.js
> +require('env2')('.config.env');
config.env not .config.env

2018-01-24 10:57 UTC, merged